---
title: "Awards"
---

**Associate Dean Fellowship.** Winter 2021. A UCI fellowship that covers a quarter of TA salary.

**Ford Fellowship Honorable Mention.** Spring 2020. Honorable mention for the prestigious Ford Fellowship on a project dealing with the ethical use if intersectional theory in studying Twitter data. 

**Provost Fellow.** UC Irvine’s recruitment fellowship for an incoming graduate student. Intended for only the top 5% of admitted graduate students. 2018-Present.

**Podlich Fellow.** UC Irvine’s Center for the Study of Democracy’s summer fellowship for incoming graduate students. Summer 2019.

**DECADE Travel Grant.** Awarded to attend Midwestern Political Science Conference, not collected due to COVID-19 cancellations. Spring  2019.

**Competitive Edge Participant.** UC Irvine Summer fellowship for incoming graduate students receiving the Diversity Recruitment Fellowships. Includes a research assistant position and training. Summer 2018. 

**Blackwell Award Winner.** Francis Marion University’s award for highest graduating GPA (4.0). Spring 2018.

**Duane P. Meyers Award.** Given to the top academic achieving senior for the FMU Honors Program –Spring 2018. 

**Scholastic Achievement Award.** Given to the highest academic achieving and community oriented seniors in FMU graduating class –Spring 2018.

**President’s Undergraduate Research Award (FMU).** Most outstanding undergraduate research piece produced in that year, presented by the President of Francis Marion University– April 2018. 

**FMU Political Science Award.** Highest achieving political science student for FMU political science department – April 2018. 

**FMU Economics Award.** Highest achieving economics student for FMU economics department – April 2018. 

**FMU Scholastic Achievement Award.** One of a small group of the highest achieving student for FMU – April 2018.

**Carlanna Hendricks Swampfox Academic Award.** The highest academic award of the FMU athletics department – April 2017. 

**Dr. Jesse A. Coles Public Service Award.** Public service award for FMU political science department – April 2017. 

**Peach Belt Conference All Academic Team.** The highest academic achievers in conference for that season, women’s soccer 2016-2017. 

**Division II ADA Athletic Achievement Award.** The award program recognizes the academic accomplishments of student-athletes at the Division II level, women’s soccer – 2016-2017. 

**FMU Honors Ambassador, Ireland.** Program that chooses four honors students to provide a scholarship to represent FMU abroad on a week-long trip to university exchange partners and that is fully funded—March 2018. 

**FMU President’s List.** Six consecutive semesters of a GPA that is 3.75 or higher—Fall 2014 to Spring 2017. 

**Peach Belt Conference Presidential Gold Scholar Honor Roll.** Highest academic recognition in conference, requires GPA of 3.75 or higher—Fall 2015 to Spring 2017.

**FMU Swampfox Academic Athletic Presidential Honor Roll.** Highest academic recognition for student-athletes, which requires GPA of 3.75 or higher—Spring 2015 to Fall 2017. 

**Patriot Scholar.** The highest academic scholarship for out-of-state residents available to FMU students based on GPA, SAT/ACT scores, and interview—Fall 2014 to Spring 2018. 

