---
title: "Methods and Coding Reading Group"
---

I founded this group to be a collaborative space meant to cross the bridges of Political Science subfields to connect folks who are wanting or are actively using quantitative methods in their work. Our goals for the group are to reduce barriers and encourage the use of quant while recognizing that Political Methodology's history as a subfield has lacked diversity and accessibility to womxn and POC. 

We are looking to embrace our collective knowledge to teach each other general methods, coding hacks, and tricks to make all of our lives easier. This space will use R, as R's open nature allows for everyone to access the software with no financial barriers. Liz and I will be hosting a few meetings, as well as allowing other grad students to pitch short hacks or packages they find helpful. We will also hold the space to read and discuss big issues/articles in Political Methodology.

**Meeting Schedulue:**

- _December 10th 3:00-4:00 PM on Github and Version Control_

- _January 15th 12:00-1:30 PM on R Bootcamp_

- _January 25th 2:00-3:00 PM on Easy Data Viz: Mia & Kyle_

- _Februrary 22th 2:00-3:00 PM on Rvest: Paul Love_

- _March 22th 2:00-3:00 PM on Network Analysis Intro: Ben & Uras_

- _April 26th 2:00-3:00 PM on Causal Inference Methods_

- _May 24th 2:00-3:00 PM on Statistical Significance Revolution_

- _June 7th 2:00-3:00 PM Regression for P.S.*_

