---
title: "Research"
---

**“Multilevel Modeling for Intersectional Effects on Political Behavior”** In progress solo-authored paper. Analyzes the use of multilevel Bayesian models for estimating the interrelated nature of race/gender/class in political behavior models. Estimated completion Spring 2021. 

**“Intersectional Reckoning: Quantitative Methods and Political Behavior.”** In progress solo-authored paper on quantitative methods, feminist theory, and Bayesian subjective priors. Estimated completion Spring 2021. 

**“Where Machine Learning Meets Feminist Theory.”** In progress solo-authored paper on political Twitter data lived experience, feminist theory and unsupervised machine learning algorithms. Estimated completion Winter 2021. 

**“Self-Reliance and Political Participation: Rethinking Self Reliance.”** In progress co-authored paper with Prof. Ines Levin, redefining self-reliance and its effects on political behavior using Stan programming and Bayesian analysis. Estimated completion Winter 2021.

**“Model-Based Clustering with Covariates & the Civic Voluntarism Model”** In progress co-authored paper with Prof. Ines Levin, re-evaluating conventional wisdom on political participation through the use of finite mixture models. Estimated completion Winter 2021. 

**“Gender and Race in the 2016 Presidential Election: An Intersectional Approach to**
**Understanding Emotions and Political Participation.”** Solo-authored paper addressing the ways in which race and gender frame the effects of anger and fear on political participation, in the context the 2016 election. Completed Fall 2019.
