---
title: "Womxn's Caucus"
description: |
  I am the lead oranizer UCI's P.S. Womxn's Caucus.
---

Our continued aim for the Political Science Womxn’s Caucus has been to serve as 
a much-needed platform to engage with issues of diversity – race, gender, 
sexuality, etc. – through the lens of intersectionality. In our third year of 
the Womxn’s Caucus, we strive to strengthen our own department's support 
of womxn graduate students and build new, diverse, 
interdisciplinary connections within the School of Social Sciences. 
As previously outlined, the Womxn’s Caucus serves a vital purpose in our 
department as a space which empowers womxn graduate students—helping them 
navigate their academic endeavors in a safe,comfortable environment that 
validates their everyday struggles and fosters their growth and learning.
Please email me at mmuch@uci.edu or jtaghvai@uci.edu for invites to these events.

**Event Schedule**

Welcome Event: _November 6th 4:00 pm_

Invited Talk with Dr. Julia Jordan Zachery: _December 2nd 11-12:30 pm PST_